### ISSUE TITLE
Proxying through Apache, nginx, Caddy, or similar

### ISSUE THREAD

**Issue by Fastidious** [key-networks/ztncui-containerized#1]
Got the docker container running. Is it possible to run it on `http` locally accessible only? How would I go to do that? I am hoping to use Apache, nginx, or Caddy as the frontend. Thanks!

**Comment by key-networks** [comment]
Hi @Fastidious,

Could you try the following and let me know if this does what you require?

docker run --net="host" --name ztncui --volume ztncui:/opt/key-networks/ztncui/etc/ --volume zt1:/var/lib/zerotier-one/ --cap-add=NET_ADMIN keynetworks/ztncui

This should make the container and host share the same network, so you should be able to connect to http://localhost:3000 on the host machine.

Steve
