### ISSUE TITLE
how to access 9993 from outside?

### ISSUE THREAD

**Issue by connected201** [key-networks/ztncui-containerized#13]
i try to write in .env ZT_ADDR=0.0.0.0:9995
but not working, other parameters like HTTP_PORT=3456 or HTTPS_PORT=3443 work well.
![Screenshot_20200429_000743](https://user-images.githubusercontent.com/20506433/80538013-a7748400-89ad-11ea-9d35-64275a2dcf63.png)
i cannot acces it from outside, because port not accept requests from outside, only from container

**Comment by connected201** [comment]
i resolved
instruction:
create or edit /var/lib/zerotier-one/local.conf
and add:
{
	"physical": {
		"10.0.0.0/24": {
			"blacklist": false
		},
		"10.10.10.0/24": {
			"trustedPathId": 101010024
		}
	},
	"virtual": {
		"feedbeef12": {
			"role": "UPSTREAM",
			"try": [ "0.0.0.0/9993" ]
			
		}
	},
	"settings": {
		"allowManagementFrom": ["0.0.0.0"],
		"softwareUpdate": "apply",
		"softwareUpdateChannel": "release"
	}
}

**Comment by key-networks** [comment]
Thanks for your feedback.
