### ISSUE TITLE
Issue when mapping volumes

### ISSUE THREAD

**Issue by ovizii** [key-networks/ztncui-containerized#14]
First of all when running this way it works:
`docker run --name ztncui -dp 3443:3443 --cap-add=NET_ADMIN keynetworks/ztncui`

as soon as I use docker-compose.yml and map a volume like this:
```
        volumes:
          - '/my/docker-data/ztncui/ui:/opt/key-networks/ztncui/etc/'
          - '/my/docker-data/ztncui/zt:/var/lib/zerotier-one/'
```

The logs say:
```
docker logs -f ztncui
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'etc/tls/fullchain.pem'

```

and indeed:
```
ls -al /my/docker-data/ztncui/ui/
total 50
drwxrwxrwx 3 systemd-coredump docker  3 May 20 23:13 .
drwxrwxrwx 4 systemd-coredump docker  4 May 20 23:13 ..
drwxr-xr-x 2 netdata          netdata 2 May 20 23:13 storage

```

but if I enter the running container started with docker run there is much more in the etc folder:
`docker exec -ti ztncui sh
`

```
sh-4.2# ls -al /opt/key-networks/ztncui/etc/
total 11
drwxrwxr-x 4 ztncui ztncui   6 May 20 21:31 .
drwxrwxr-x 4 ztncui ztncui   6 Aug 17  2019 ..
-rw------- 1 ztncui ztncui 148 Aug 17  2019 default.passwd
-rw------- 1 ztncui ztncui 148 Aug 17  2019 passwd
drwxr-xr-x 2 ztncui ztncui   2 May 20 21:31 storage
drwxrwxr-x 2 ztncui ztncui   4 Aug 17  2019 tls

```

There is something wrong here! Anyone got any ideas?

**Comment by mdPlusPlus** [comment]
Maybe it's related to this: https://github.com/key-networks/ztncui-containerized/issues/4#issuecomment-565754035

**Comment by key-networks** [comment]
Possibly.  Are you also running Ubuntu 19.10 as the Docker host?

**Comment by ovizii** [comment]
> Possibly. Are you also running Ubuntu 19.10 as the Docker host?
Nope, I am running Debian 10 on my NAS where I was trying to run this container.

**Comment by key-networks** [comment]
Debian and Ubuntu are close relatives.  It might be better to run just the Zerotier-one client on your NAS and host the controller somewhere else.

**Comment by ovizii** [comment]
thanks.
