### ISSUE TITLE
What exactly does this image contain?

### ISSUE THREAD

**Issue by ovizii** [key-networks/ztncui-containerized#15]
The description says:

`This is a Docker image that contains ZeroTier One and ztncui to set up a standalone ZeroTier network controller with a web user interface in a container.`

That sounds like I only need to run a container based on this image and then another client to connect them but it seems like this does only run the network controller so if my client wants to connect to the docker host, I still need to run zerotier one locally on the host in addition to this docker container, right?

**Comment by key-networks** [comment]
The host would be a separate client to the container.  Typically the container is just for the network controller and should not be a client in the network.

**Comment by ovizii** [comment]
thanks.
