### ISSUE TITLE
New zero-tier package version

### ISSUE THREAD

**Issue by warren-ru** [key-networks/ztncui-containerized#18]
Zero-tier 1.6.0 version has been released.
Are you going to update ztncui docker image?

**Comment by key-networks** [comment]
Version 1.2.5, which includes ztncui 0.6.6 and zerotier-one-1.6.2 has just been published at https://hub.docker.com/repository/docker/keynetworks/ztncui

**Comment by key-networks** [comment]
Version 1.2.6 has been published.  It fixes issues with volume mounts and provides a simple file sharing mechanism.  It is now based on https://github.com/key-networks/ztncui-aio
