### ISSUE TITLE
Error resolving detail for network ***********: HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by maryjeck** [key-networks/ztncui-containerized#34]
When I create the docker container, it works fine. He used 1.10.6, but I manually upgraded to 1.12.1, it appeared this "Error resolving detail for network ***********: HTTPError: Response code 404 (Not Found)"

Is there any solution?

**Comment by AndyDavis8** [comment]
Pls check here:  
[https://github.com/key-networks/ztncui/issues/123](https://github.com/key-networks/ztncui/issues/123)

**Comment by key-networks** [comment]
Addressed here https://github.com/key-networks/ztncui/issues/123
