### ISSUE TITLE
Problem logging in as admin with default password

### ISSUE THREAD

**Issue by Deanosim** [key-networks/ztncui-containerized#5]
So I just got this docker up and running but I can't sign into the web ui, it just times out loading and I get this error message in the docker log.

`(node:11) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'etc/passwd'`
`(node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)`

**Comment by key-networks** [comment]
Could you please let us know your operating environment - what OS, what version of Docker, etc?
